//! Auto-generated banner injected at the top of every rendered file.
//!
//! The banner is a write-side concern, not a render-side concern. Keeping it
//! out of `render_for_provider` preserves the byte-identical regression gate
//! in `tests/templates_render.rs`.

#![deny(clippy::unwrap_used)]
#![deny(clippy::expect_used)]

pub fn with_banner(rendered: &str, command: &str) -> String {
    format!(
        "<!-- AUTO-GENERATED by maestro sync-templates from .maestro/templates/commands/{command}.md. DO NOT EDIT. -->\n\n{rendered}"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn with_banner_prepends_constant_prefix_and_blank_line() {
        let result = with_banner("# Hello\nworld", "implement");
        assert!(result.starts_with("<!-- AUTO-GENERATED by maestro sync-templates from "));
        assert!(result.contains("\n\n# Hello\nworld"));
        assert!(result.contains("-->"));
    }

    #[test]
    fn with_banner_interpolates_command_name_into_source_reference() {
        let result = with_banner("body", "plan-feature");
        assert!(result.contains(".maestro/templates/commands/plan-feature.md"));
    }

    #[test]
    fn with_banner_applied_twice_does_not_strip_first_banner() {
        // DESIGN: with_banner is not idempotent. Callers (SyncRunner::run)
        // must ensure they call it exactly once per write.
        let second = with_banner(&with_banner("body", "implement"), "implement");
        let banner_count = second.matches("<!-- AUTO-GENERATED").count();
        assert_eq!(banner_count, 2);
    }
}
