//! `.maestro/templates.lock` schema and serialization.
//!
//! The lockfile is a deterministic TOML record of every repo-relative rendered
//! file: provider, command, and SHA-256 of the on-disk bytes (banner included).
//! Cache writes (HTTP-only providers) are intentionally NOT tracked — they live
//! outside the repo and would break cross-machine reproducibility.

#![deny(clippy::unwrap_used)]
#![deny(clippy::expect_used)]

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

use crate::commands::sync_templates::SyncTemplatesError;

const LOCKFILE_HEADER: &str =
    "# .maestro/templates.lock — AUTO-GENERATED by maestro sync-templates. DO NOT EDIT.\n\n";

#[derive(Debug, Serialize, Deserialize, PartialEq, Eq, Clone)]
#[serde(deny_unknown_fields)]
pub struct Lockfile {
    pub schema_version: u32,
    #[serde(default)]
    pub files: BTreeMap<String, FileEntry>,
}

#[derive(Debug, Serialize, Deserialize, PartialEq, Eq, Clone)]
#[serde(deny_unknown_fields)]
pub struct FileEntry {
    pub provider: String,
    pub command: String,
    pub sha256: String,
}

impl Lockfile {
    pub fn new() -> Self {
        Self {
            schema_version: 1,
            files: BTreeMap::new(),
        }
    }

    pub fn to_toml_string(&self) -> Result<String, SyncTemplatesError> {
        let body = toml::to_string(self)
            .map_err(|e| SyncTemplatesError::LockfileSerialize(Box::new(e)))?;
        Ok(format!("{LOCKFILE_HEADER}{body}"))
    }

    pub fn insert(&mut self, rel_path: String, entry: FileEntry) {
        self.files.insert(rel_path, entry);
    }
}

impl Default for Lockfile {
    fn default() -> Self {
        Self::new()
    }
}

pub fn sha256_hex(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    format!("{:x}", hasher.finalize())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_returns_empty_lockfile_with_schema_version_1() {
        let lf = Lockfile::new();
        assert_eq!(lf.schema_version, 1);
        assert!(lf.files.is_empty());
    }

    #[test]
    fn to_toml_string_starts_with_header_comment() {
        let lf = Lockfile::new();
        let s = lf.to_toml_string().expect("serialize");
        assert!(
            s.starts_with(
                "# .maestro/templates.lock — AUTO-GENERATED by maestro sync-templates. DO NOT EDIT."
            ),
            "got: {s:.120}"
        );
    }

    #[test]
    fn to_toml_string_serializes_files_in_sorted_key_order() {
        let mut lf = Lockfile::new();
        lf.files.insert(
            ".claude/commands/pushup.md".to_string(),
            FileEntry {
                provider: "claude".into(),
                command: "pushup".into(),
                sha256: "aaa".into(),
            },
        );
        lf.files.insert(
            ".claude/commands/implement.md".to_string(),
            FileEntry {
                provider: "claude".into(),
                command: "implement".into(),
                sha256: "bbb".into(),
            },
        );
        let s = lf.to_toml_string().expect("serialize");
        let implement_pos = s.find(".claude/commands/implement.md").expect("implement");
        let pushup_pos = s.find(".claude/commands/pushup.md").expect("pushup");
        assert!(
            implement_pos < pushup_pos,
            "keys must be sorted: implement before pushup"
        );
    }

    #[test]
    fn to_toml_string_is_byte_identical_across_two_calls_for_same_input() {
        let mut lf = Lockfile::new();
        lf.files.insert(
            ".claude/commands/implement.md".to_string(),
            FileEntry {
                provider: "claude".into(),
                command: "implement".into(),
                sha256: "cafebabe".into(),
            },
        );
        let s1 = lf.to_toml_string().expect("first");
        let s2 = lf.to_toml_string().expect("second");
        assert_eq!(s1, s2, "serialization must be deterministic");
    }

    #[test]
    fn sha256_hex_returns_known_value_for_empty_input() {
        assert_eq!(
            sha256_hex(b""),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
    }

    #[test]
    fn sha256_hex_returns_known_value_for_hello_world() {
        assert_eq!(
            sha256_hex(b"hello world"),
            "b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9"
        );
    }
}
