use super::client::GitHubClient;
use super::types::GhIssue;
use anyhow::Result;

/// Build the PR body for an issue.
pub fn build_pr_body(issue: &GhIssue, files_touched: &[&str], cost_usd: f64) -> String {
    let mut body = String::new();
    body.push_str(&format!("Closes #{}\n\n", issue.number));
    body.push_str("## Summary\n\n");
    body.push_str(&format!(
        "Automated implementation for issue #{}: {}\n\n",
        issue.number, issue.title
    ));

    if !files_touched.is_empty() {
        body.push_str("## Files Changed\n\n");
        for file in files_touched {
            body.push_str(&format!("- `{}`\n", file));
        }
        body.push('\n');
    }

    body.push_str("## Cost Report\n\n");
    body.push_str(&format!("- **Cost**: ${:.2}\n", cost_usd));
    body.push_str("\n---\n*Generated by [Maestro](https://github.com/maestro)*\n");
    body
}

pub struct PrCreator<C: GitHubClient> {
    client: C,
    base_branch: String,
}

impl<C: GitHubClient> PrCreator<C> {
    pub fn new(client: C, base_branch: String) -> Self {
        Self {
            client,
            base_branch,
        }
    }

    /// Create a PR for a completed issue session.
    pub async fn create_for_issue(
        &self,
        issue: &GhIssue,
        head_branch: &str,
        files_touched: &[&str],
        cost_usd: f64,
    ) -> Result<u64> {
        let title = format!("[Maestro] #{} {}", issue.number, issue.title);
        let body = build_pr_body(issue, files_touched, cost_usd);

        self.client
            .create_pr(issue.number, &title, &body, head_branch, &self.base_branch)
            .await
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::github::client::mock::MockGitHubClient;

    fn make_issue(number: u64) -> GhIssue {
        GhIssue {
            number,
            title: format!("Implement feature #{}", number),
            body: String::new(),
            labels: vec!["maestro:in-progress".to_string()],
            state: "open".to_string(),
            html_url: format!("https://github.com/owner/repo/issues/{}", number),
        }
    }

    #[test]
    fn build_pr_body_contains_closes_reference() {
        let issue = make_issue(42);
        let body = build_pr_body(&issue, &[], 1.23);
        assert!(
            body.contains("Closes #42"),
            "PR body must reference the issue with 'Closes #42'"
        );
    }

    #[test]
    fn build_pr_body_contains_cost() {
        let issue = make_issue(1);
        let body = build_pr_body(&issue, &["src/main.rs"], 2.50);
        assert!(
            body.contains("2.50") || body.contains("$2.50"),
            "PR body must include the session cost"
        );
    }

    #[test]
    fn build_pr_body_lists_touched_files() {
        let issue = make_issue(1);
        let files = vec!["src/github/types.rs", "src/github/client.rs"];
        let body = build_pr_body(&issue, &files, 0.0);
        assert!(body.contains("src/github/types.rs"));
        assert!(body.contains("src/github/client.rs"));
    }

    #[test]
    fn build_pr_body_empty_files_list() {
        let issue = make_issue(5);
        let body = build_pr_body(&issue, &[], 0.0);
        assert!(body.contains("Closes #5"));
    }

    #[tokio::test]
    async fn create_for_issue_calls_create_pr_with_correct_args() {
        let client = MockGitHubClient::new();
        client.set_create_pr_response(99);
        let creator = PrCreator::new(client.clone(), "main".to_string());

        let issue = make_issue(10);
        let pr_number = creator
            .create_for_issue(&issue, "maestro/issue-10", &["src/lib.rs"], 0.75)
            .await
            .unwrap();

        assert_eq!(pr_number, 99);

        let calls = client.create_pr_calls();
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].issue_number, 10);
        assert_eq!(calls[0].head_branch, "maestro/issue-10");
        assert_eq!(calls[0].base_branch, "main");
        assert!(calls[0].body.contains("Closes #10"));
    }

    #[tokio::test]
    async fn create_for_issue_propagates_github_error() {
        let client = MockGitHubClient::new();
        client.set_create_pr_error("branch already has open PR");
        let creator = PrCreator::new(client, "main".to_string());

        let issue = make_issue(1);
        let result = creator
            .create_for_issue(&issue, "maestro/issue-1", &[], 0.0)
            .await;

        assert!(result.is_err());
        assert!(
            result
                .unwrap_err()
                .to_string()
                .contains("branch already has open PR")
        );
    }

    #[tokio::test]
    async fn create_for_issue_pr_title_includes_issue_title() {
        let client = MockGitHubClient::new();
        let creator = PrCreator::new(client.clone(), "main".to_string());

        let issue = make_issue(7);
        creator
            .create_for_issue(&issue, "maestro/issue-7", &[], 0.0)
            .await
            .unwrap();

        let calls = client.create_pr_calls();
        assert!(
            calls[0].title.contains("Implement feature #7") || calls[0].title.contains("#7"),
            "PR title must reference the issue"
        );
    }
}
