use super::client::GitHubClient;
use super::types::GhIssue;
use anyhow::Result;
use std::time::Duration;

/// Append shared footer sections (Files Changed, Cost Report, branding) to a PR body.
fn append_pr_footer(body: &mut String, files_touched: &[&str], cost_usd: f64) {
    if !files_touched.is_empty() {
        body.push_str("## Files Changed\n\n");
        for file in files_touched {
            body.push_str(&format!("- `{}`\n", file));
        }
        body.push('\n');
    }

    body.push_str("## Cost Report\n\n");
    body.push_str(&format!("- **Cost**: ${:.2}\n", cost_usd));
    body.push_str("\n---\n*Generated by [Maestro](https://github.com/maestro)*\n");
}

/// Build the PR body for an issue.
pub fn build_pr_body(issue: &GhIssue, files_touched: &[&str], cost_usd: f64) -> String {
    let mut body = String::new();
    body.push_str(&format!("Closes #{}\n\n", issue.number));
    body.push_str("## Summary\n\n");
    body.push_str(&format!(
        "Automated implementation for issue #{}: {}\n\n",
        issue.number, issue.title
    ));
    append_pr_footer(&mut body, files_touched, cost_usd);
    body
}

/// Build a PR body that closes multiple issues (unified PR).
pub fn build_unified_pr_body(issues: &[&GhIssue], files_touched: &[&str], cost_usd: f64) -> String {
    let mut body = String::new();

    for issue in issues {
        body.push_str(&format!("Closes #{}\n", issue.number));
    }
    body.push('\n');

    body.push_str("## Summary\n\n");
    body.push_str("Unified implementation for multiple issues:\n\n");
    for issue in issues {
        body.push_str(&format!("- **#{}**: {}\n", issue.number, issue.title));
    }
    body.push('\n');

    append_pr_footer(&mut body, files_touched, cost_usd);
    body
}

/// Generate a deterministic branch name for a unified PR.
/// Issues are sorted for consistency: `maestro/unified-17-42-100`.
pub fn unified_branch_name(issue_numbers: &[u64]) -> String {
    let mut sorted = issue_numbers.to_vec();
    sorted.sort();
    let joined: Vec<String> = sorted.iter().map(|n| n.to_string()).collect();
    format!("maestro/unified-{}", joined.join("-"))
}

pub struct PrCreator<C: GitHubClient> {
    client: C,
    base_branch: String,
}

impl<C: GitHubClient> PrCreator<C> {
    pub fn new(client: C, base_branch: String) -> Self {
        Self {
            client,
            base_branch,
        }
    }

    /// Create a PR for a completed issue session.
    pub async fn create_for_issue(
        &self,
        issue: &GhIssue,
        head_branch: &str,
        files_touched: &[&str],
        cost_usd: f64,
    ) -> Result<u64> {
        let title = format!("[Maestro] #{} {}", issue.number, issue.title);
        let body = build_pr_body(issue, files_touched, cost_usd);

        self.client
            .create_pr(issue.number, &title, &body, head_branch, &self.base_branch)
            .await
    }
}

/// Retry configuration for PR creation.
#[derive(Debug, Clone)]
pub struct PrRetryPolicy {
    pub max_attempts: u32,
    pub base_delay_secs: u64,
    pub multiplier: u64,
}

impl Default for PrRetryPolicy {
    fn default() -> Self {
        Self {
            max_attempts: 3,
            base_delay_secs: 5,
            multiplier: 3,
        }
    }
}

impl PrRetryPolicy {
    /// Calculate delay for attempt N (0-indexed). Returns None if retries exhausted.
    pub fn delay_for_attempt(&self, attempt: u32) -> Option<Duration> {
        if attempt >= self.max_attempts {
            return None;
        }
        let secs = self
            .multiplier
            .checked_pow(attempt)
            .and_then(|m| self.base_delay_secs.checked_mul(m))
            .unwrap_or(u64::MAX);
        Some(Duration::from_secs(secs))
    }
}

/// A remote branch with no corresponding open PR.
#[derive(Debug, Clone)]
#[allow(dead_code)] // Reason: orphan branch cleanup feature
pub struct OrphanBranch {
    pub branch: String,
    pub issue_number: Option<u64>,
}

#[allow(dead_code)] // Reason: orphan branch cleanup feature
impl OrphanBranch {
    /// Parse an issue number from a branch name like "maestro/issue-42".
    pub fn from_branch_name(branch: &str) -> Self {
        let issue_number = branch
            .strip_prefix("maestro/issue-")
            .or_else(|| branch.strip_prefix("origin/maestro/issue-"))
            .and_then(|rest| rest.parse::<u64>().ok());
        Self {
            branch: branch.to_string(),
            issue_number,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::provider::github::client::mock::MockGitHubClient;

    fn make_issue(number: u64) -> GhIssue {
        GhIssue {
            number,
            title: format!("Implement feature #{}", number),
            body: String::new(),
            labels: vec!["maestro:in-progress".to_string()],
            state: "open".to_string(),
            html_url: format!("https://github.com/owner/repo/issues/{}", number),
            milestone: None,
            assignees: vec![],
        }
    }

    #[test]
    fn build_pr_body_contains_closes_reference() {
        let issue = make_issue(42);
        let body = build_pr_body(&issue, &[], 1.23);
        assert!(
            body.contains("Closes #42"),
            "PR body must reference the issue with 'Closes #42'"
        );
    }

    #[test]
    fn build_pr_body_contains_cost() {
        let issue = make_issue(1);
        let body = build_pr_body(&issue, &["src/main.rs"], 2.50);
        assert!(
            body.contains("2.50") || body.contains("$2.50"),
            "PR body must include the session cost"
        );
    }

    #[test]
    fn build_pr_body_lists_touched_files() {
        let issue = make_issue(1);
        let files = vec!["src/github/types.rs", "src/github/client.rs"];
        let body = build_pr_body(&issue, &files, 0.0);
        assert!(body.contains("src/github/types.rs"));
        assert!(body.contains("src/github/client.rs"));
    }

    #[test]
    fn build_pr_body_empty_files_list() {
        let issue = make_issue(5);
        let body = build_pr_body(&issue, &[], 0.0);
        assert!(body.contains("Closes #5"));
    }

    #[tokio::test]
    async fn create_for_issue_calls_create_pr_with_correct_args() {
        let client = MockGitHubClient::new();
        client.set_create_pr_response(99);
        let creator = PrCreator::new(client.clone(), "main".to_string());

        let issue = make_issue(10);
        let pr_number = creator
            .create_for_issue(&issue, "maestro/issue-10", &["src/lib.rs"], 0.75)
            .await
            .unwrap();

        assert_eq!(pr_number, 99);

        let calls = client.create_pr_calls();
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].issue_number, 10);
        assert_eq!(calls[0].head_branch, "maestro/issue-10");
        assert_eq!(calls[0].base_branch, "main");
        assert!(calls[0].body.contains("Closes #10"));
    }

    #[tokio::test]
    async fn create_for_issue_propagates_github_error() {
        let client = MockGitHubClient::new();
        client.set_create_pr_error("branch already has open PR");
        let creator = PrCreator::new(client, "main".to_string());

        let issue = make_issue(1);
        let result = creator
            .create_for_issue(&issue, "maestro/issue-1", &[], 0.0)
            .await;

        assert!(result.is_err());
        assert!(
            result
                .unwrap_err()
                .to_string()
                .contains("branch already has open PR")
        );
    }

    // --- Issue #159: PrRetryPolicy tests ---

    #[test]
    fn retry_policy_default_values() {
        let policy = PrRetryPolicy::default();
        assert_eq!(policy.max_attempts, 3);
        assert_eq!(policy.base_delay_secs, 5);
        assert_eq!(policy.multiplier, 3);
    }

    #[test]
    fn retry_policy_delay_attempt_0_is_5s() {
        let policy = PrRetryPolicy::default();
        assert_eq!(policy.delay_for_attempt(0), Some(Duration::from_secs(5)));
    }

    #[test]
    fn retry_policy_delay_attempt_1_is_15s() {
        let policy = PrRetryPolicy::default();
        assert_eq!(policy.delay_for_attempt(1), Some(Duration::from_secs(15)));
    }

    #[test]
    fn retry_policy_delay_attempt_2_is_45s() {
        let policy = PrRetryPolicy::default();
        assert_eq!(policy.delay_for_attempt(2), Some(Duration::from_secs(45)));
    }

    #[test]
    fn retry_policy_delay_attempt_3_is_exhausted() {
        let policy = PrRetryPolicy::default();
        assert_eq!(policy.delay_for_attempt(3), None);
    }

    #[test]
    fn retry_policy_delay_attempt_beyond_max_is_none() {
        let policy = PrRetryPolicy::default();
        assert_eq!(policy.delay_for_attempt(100), None);
    }

    #[test]
    fn retry_policy_custom_values() {
        let policy = PrRetryPolicy {
            max_attempts: 2,
            base_delay_secs: 10,
            multiplier: 2,
        };
        assert_eq!(policy.delay_for_attempt(0), Some(Duration::from_secs(10)));
        assert_eq!(policy.delay_for_attempt(1), Some(Duration::from_secs(20)));
        assert_eq!(policy.delay_for_attempt(2), None);
    }

    #[test]
    fn retry_policy_delays_are_strictly_increasing() {
        let policy = PrRetryPolicy::default();
        let delays: Vec<Duration> = (0..3)
            .map(|i| policy.delay_for_attempt(i).expect("attempt within range"))
            .collect();
        for window in delays.windows(2) {
            assert!(window[1] > window[0], "delays must be strictly increasing");
        }
    }

    // --- Issue #159: OrphanBranch tests ---

    #[test]
    fn orphan_branch_parses_issue_number_from_maestro_prefix() {
        let ob = OrphanBranch::from_branch_name("maestro/issue-42");
        assert_eq!(ob.issue_number, Some(42));
        assert_eq!(ob.branch, "maestro/issue-42");
    }

    #[test]
    fn orphan_branch_parses_issue_number_from_origin_prefix() {
        let ob = OrphanBranch::from_branch_name("origin/maestro/issue-99");
        assert_eq!(ob.issue_number, Some(99));
    }

    #[test]
    fn orphan_branch_returns_none_for_non_matching_branch() {
        let ob = OrphanBranch::from_branch_name("feat/something");
        assert_eq!(ob.issue_number, None);
    }

    #[test]
    fn orphan_branch_returns_none_for_non_numeric_suffix() {
        let ob = OrphanBranch::from_branch_name("maestro/issue-abc");
        assert_eq!(ob.issue_number, None);
    }

    // --- Issue #301: Unified PR tests ---

    #[test]
    fn unified_pr_body_contains_all_closes_refs() {
        let i1 = make_issue(42);
        let i2 = make_issue(99);
        let body = build_unified_pr_body(&[&i1, &i2], &[], 0.0);
        assert!(body.contains("Closes #42"));
        assert!(body.contains("Closes #99"));
    }

    #[test]
    fn unified_pr_body_lists_all_issue_titles() {
        let i1 = make_issue(10);
        let i2 = make_issue(20);
        let i3 = make_issue(30);
        let body = build_unified_pr_body(&[&i1, &i2, &i3], &[], 0.0);
        assert!(body.contains("**#10**"));
        assert!(body.contains("**#20**"));
        assert!(body.contains("**#30**"));
    }

    #[test]
    fn unified_pr_body_includes_cost() {
        let i1 = make_issue(1);
        let body = build_unified_pr_body(&[&i1], &["src/lib.rs"], 3.45);
        assert!(body.contains("$3.45"));
    }

    #[test]
    fn unified_pr_body_includes_files() {
        let i1 = make_issue(1);
        let body = build_unified_pr_body(&[&i1], &["src/a.rs", "src/b.rs"], 0.0);
        assert!(body.contains("src/a.rs"));
        assert!(body.contains("src/b.rs"));
    }

    #[test]
    fn unified_branch_name_sorts_and_joins() {
        assert_eq!(
            unified_branch_name(&[42, 17, 100]),
            "maestro/unified-17-42-100"
        );
    }

    #[test]
    fn unified_branch_name_single_issue() {
        assert_eq!(unified_branch_name(&[5]), "maestro/unified-5");
    }

    #[test]
    fn unified_branch_name_already_sorted() {
        assert_eq!(unified_branch_name(&[1, 2, 3]), "maestro/unified-1-2-3");
    }

    #[tokio::test]
    async fn create_for_issue_pr_title_includes_issue_title() {
        let client = MockGitHubClient::new();
        let creator = PrCreator::new(client.clone(), "main".to_string());

        let issue = make_issue(7);
        creator
            .create_for_issue(&issue, "maestro/issue-7", &[], 0.0)
            .await
            .unwrap();

        let calls = client.create_pr_calls();
        assert!(
            calls[0].title.contains("Implement feature #7") || calls[0].title.contains("#7"),
            "PR title must reference the issue"
        );
    }
}
