//! Merge a freshly rendered TOML template into a user's existing
//! `maestro.toml`, preserving every key the user has set on disk.
//!
//! Merge rule (definitive): a key is "user-customized" iff it exists in
//! the existing TOML at the same dotted path. Keys present in defaults
//! but missing from existing are added. Keys present only in existing
//! are kept. Scalars are never overwritten.

use anyhow::{Context, Result};
use toml::Value;

/// Outcome of a merge: the bytes to write back, plus dotted-path lists
/// for user-facing reporting.
#[derive(Debug, Clone, PartialEq)]
pub struct MergeReport {
    pub merged_toml: String,
    pub keys_added: Vec<String>,
    pub keys_preserved: Vec<String>,
}

/// Merge `defaults_toml` into `existing_toml`, preserving user values.
pub fn merge_preserving_user_keys(existing_toml: &str, defaults_toml: &str) -> Result<MergeReport> {
    let mut existing: Value =
        toml::from_str(existing_toml).context("parsing existing maestro.toml")?;
    let defaults: Value =
        toml::from_str(defaults_toml).context("parsing detected defaults TOML")?;

    let mut keys_added = Vec::new();
    let mut keys_preserved = Vec::new();

    merge_values(
        &mut existing,
        &defaults,
        "",
        &mut keys_added,
        &mut keys_preserved,
    );

    let merged = toml::to_string_pretty(&existing).context("serializing merged TOML")?;
    let header = "# Re-generated by `maestro init --reset`.\n\
                  # Original comments were not preserved (TOML parser limitation).\n\
                  # Customized values are preserved verbatim.\n";

    Ok(MergeReport {
        merged_toml: format!("{header}{merged}"),
        keys_added,
        keys_preserved,
    })
}

fn merge_values(
    existing: &mut Value,
    defaults: &Value,
    path: &str,
    added: &mut Vec<String>,
    preserved: &mut Vec<String>,
) {
    let (Value::Table(existing_tbl), Value::Table(defaults_tbl)) = (existing, defaults) else {
        return;
    };

    for (key, default_val) in defaults_tbl.iter() {
        let dotted = if path.is_empty() {
            key.clone()
        } else {
            format!("{path}.{key}")
        };
        match existing_tbl.get_mut(key) {
            None => {
                existing_tbl.insert(key.clone(), default_val.clone());
                added.push(dotted);
            }
            Some(existing_val) => match (existing_val, default_val) {
                (Value::Table(_), Value::Table(_)) => {
                    if let Some(child) = existing_tbl.get_mut(key) {
                        merge_values(child, default_val, &dotted, added, preserved);
                    }
                }
                _ => {
                    preserved.push(dotted);
                }
            },
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn merge_preserves_custom_key() {
        let existing = "[project]\nlanguage = \"rust\"\ncustom_key = \"foo\"\n";
        let defaults = "[project]\nlanguage = \"rust\"\nbuild_command = \"cargo build\"\n";
        let report = merge_preserving_user_keys(existing, defaults).unwrap();
        assert!(
            report.merged_toml.contains("custom_key = \"foo\""),
            "{}",
            report.merged_toml
        );
        assert!(
            report
                .merged_toml
                .contains("build_command = \"cargo build\""),
            "{}",
            report.merged_toml
        );
    }

    #[test]
    fn merge_does_not_overwrite_user_value() {
        let existing = "[project]\nlanguage = \"my-custom-lang\"\n";
        let defaults = "[project]\nlanguage = \"rust\"\n";
        let report = merge_preserving_user_keys(existing, defaults).unwrap();
        assert!(
            report.merged_toml.contains("language = \"my-custom-lang\""),
            "{}",
            report.merged_toml
        );
        assert!(
            !report.merged_toml.contains("language = \"rust\""),
            "{}",
            report.merged_toml
        );
    }

    #[test]
    fn merge_adds_missing_default_key() {
        let existing = "[project]\nrepo = \"owner/repo\"\n";
        let defaults = "[project]\nrepo = \"x\"\nbuild_command = \"cargo build\"\n";
        let report = merge_preserving_user_keys(existing, defaults).unwrap();
        assert!(
            report.merged_toml.contains("repo = \"owner/repo\""),
            "{}",
            report.merged_toml
        );
        assert!(
            report
                .merged_toml
                .contains("build_command = \"cargo build\""),
            "{}",
            report.merged_toml
        );
    }

    #[test]
    fn merge_nested_table_preserves_user_key() {
        let existing = "[gates]\ntest_command = \"my test\"\ncustom_ci = \"jenkins\"\n";
        let defaults = "[gates]\ntest_command = \"cargo test\"\n";
        let report = merge_preserving_user_keys(existing, defaults).unwrap();
        assert!(
            report.merged_toml.contains("custom_ci = \"jenkins\""),
            "{}",
            report.merged_toml
        );
        assert!(
            report.merged_toml.contains("test_command = \"my test\""),
            "{}",
            report.merged_toml
        );
    }

    #[test]
    fn merge_malformed_existing_toml_returns_err() {
        let existing = "this is not valid toml = [[[";
        let defaults = "[project]\nlanguage = \"rust\"\n";
        let result = merge_preserving_user_keys(existing, defaults);
        assert!(result.is_err());
    }

    #[test]
    fn merge_malformed_defaults_toml_returns_err() {
        let existing = "[project]\nlanguage = \"rust\"\n";
        let defaults = "broken [[ no";
        let result = merge_preserving_user_keys(existing, defaults);
        assert!(result.is_err());
    }

    #[test]
    fn merge_idempotent_when_run_twice() {
        let existing = "[project]\nrepo = \"owner/repo\"\n";
        let defaults = "[project]\nrepo = \"x\"\nbuild_command = \"cargo build\"\n";
        let first = merge_preserving_user_keys(existing, defaults).unwrap();
        let second = merge_preserving_user_keys(&first.merged_toml, defaults).unwrap();
        assert_eq!(first.merged_toml.trim(), second.merged_toml.trim());
    }
}
